### ISSUE TITLE
Implement face detection processing in rabbitmq queue

### ISSUE THREAD

**Issue by alvassin** [JaneTurueva/chekist#9]
Face detector & encoder currently take a lot of time and CPU in `POST /photos` handler and we provide very poor performance.

In our aiohttp handler we could just add a row to photos table to acquire some photo_id, send photo to rabbitmq queue for later processing and return response to the user as soon as possible.

Could you please implement such separate rabbitmq handler? You can use [aio-pika](https://github.com/mosquito/aio-pika) for that. @mosquito implemented very useful [Master/Worker patterns](https://aio-pika.readthedocs.io/en/latest/patterns.html#master-worker), in aiohttp handler you could use Master pattern, in queue handler the Worker one.

Using that approach our API would be able to serve much more requests.

**Comment by JaneTurueva** [comment]
Done, closing.
